services:
  db:
    image: postgres:15
    container_name: lifesync-db
    restart: always
    environment:
      POSTGRES_DB: LifeSyncDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lifesync-net

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: lifesync-backend
    depends_on:
      - db
    restart: always
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/LifeSyncDB
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - lifesync-net

networks:
  lifesync-net:

volumes:
  postgres_data:
